### ISSUE TITLE
Hashtags - Option

### ISSUE THREAD

**Issue by apsolut** [lepture/onepage#1]
Any quick solution for adding hashtags ?

**Comment by lepture** [comment]
what do you mean?

**Comment by apsolut** [comment]
Would love custom hashtag for every section, even if i need to add them manual.  #homepage #contact etc... 

also i have problem in firefox, its working when i click buttons (pagination dots) , but when i use mouse scroll its not working...

**Comment by lepture** [comment]
@apsolut maybe firefox has no mousewheel event.
